---
AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Magento on AWS.
Parameters:
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: aws-quickstart
    Description: "S3 bucket name for the Quick Start assets. Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: ''
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: String
  AccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Description: 'The CIDR IP range that is permitted to access Magento instances.
      Note: a value of 0.0.0.0/0 will allow access from ANY ip address'
    Type: String
  AdminEmail:
    Description: Email of the Magento site administrator
    Type: String
  AdminFirstName:
    Description: First Name of the Magento site administrator
    Type: String
  AdminLastName:
    Description: Last Name of the Magento site administrator
    Type: String
  AdminPassword:
    AllowedPattern: (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*
    ConstraintDescription: Must be at least 8 characters containing letters, numbers
      and symbols.
    Description: Password of the Magento site administrator
    MaxLength: '32'
    MinLength: '8'
    NoEcho: 'True'
    Type: String
  AdminUserName:
    Description: Username of the Magento site administrator
    Type: String
  DBAutoMinorVersionUpgrade:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'true'
    Description: Select true/false to setup Auto Minor Version upgrade
    Type: String
  DBBackupRetentionPeriod:
    Default: '7'
    Description: The number of days for which automatic DB snapshots are retained.
    Type: String
  DBEngineType:
    AllowedValues:
    - Amazon Aurora
    - MySQL
    Default: Amazon Aurora
    Description: Engine to use for Magento database
    Type: String
  DBInstanceClass:
    Default: db.r5.large
    Description: The name of the compute and memory capacity class of the Amazon RDS
      (Aurora/MySQL) DB instance.
    Type: String
  DBMasterUserPassword:
    AllowedPattern: (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*
    ConstraintDescription: Must be at least 8 characters containing letters, numbers
      and symbols. It can be any printable ASCII character except /, double quotes, or @.
    Description: The database admin account password. Must be at least 8 characters containing letters, numbers and symbols. It can be any printable ASCII character except /, double quotes, or @.
    MaxLength: '32'
    MinLength: '8'
    NoEcho: 'True'
    Type: String
  DBMasterUsername:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric
      characters.
    Default: admin
    Description: The database admin account username
    MaxLength: '16'
    MinLength: '1'
    NoEcho: 'true'
    Type: String
  DBMultiAZ:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'true'
    Description: Specifies if the database instance is a multiple Availability Zone
      deployment.
    Type: String
  DBName:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric
      characters.
    Default: MagentoQuickstartDB
    Description: Name of Magento Quick Start database.
    MaxLength: '64'
    MinLength: '5'
    Type: String
  DNSName:
    Default: ''
    Description: (Optional) DNS Name for the magento site, you should create an alias
      for the ELB after the stack creation
    Type: String
  ElastiCacheAutomaticFailover:
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'true'
    Description: Select true/false to setup Automatic Failover
    Type: String
  ElastiCacheNodeType:
    Default: cache.m5.large
    Description: The name of the compute and memory capacity class of the ElastiCache
      instance.
    Type: String
  ElastiCacheNodes:
    ConstraintDescription: Must be between 2 and 5
    Default: '2'
    Description: Number of nodes in the ElastiCache cluster
    MaxValue: '5'
    MinValue: '2'
    Type: Number
  MagentoCurrency:
    Default: USD
    Description: Currency you’d like to use to display prices in the Magento store
      (Check here for the supported currency command http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html)
    Type: String
  MagentoLanguage:
    Default: en_US
    Description: The language you’d like to use for the text that appears throughout
      the Magento store (Check here for the supported Language command http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html)
    Type: String
  MagentoVersion:
    Default: '2.4'
    Description: Magento Version (2.1 / 2.3 / 2.4)
    Type: String
  MagentoUsername:
    Description: Magento access key (public)
    Type: String
  MagentoPassword:
    Description: Magenton access key (private)
    Type: String
  MagentoTimezone:
    Default: America/Los_Angeles
    Description: The time zone setting that specifies the primary market served by
      the Magento store
    Type: String
  NotificationEmail:
    AllowedPattern: ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: Must be a valid email address.
    Description: Email address to notify if there are any scaling operations
    Type: String
  PrivateSubnet1ID:
    Description: Private Subnet Id 1
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2ID:
    Description: Private Subnet Id 2
    Type: AWS::EC2::Subnet::Id
  PublicSubnet1ID:
    Description: Public Subnet Id 1
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2ID:
    Description: Public Subnet Id 2
    Type: AWS::EC2::Subnet::Id
  SSLCertificateId:
    Default: ''
    Description: (Optional) The ARN of the SSL certificate to use for the webserver.
      [optional]
    Type: String
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Description: The CIDR IP range of VPC
    Type: String
  VPCID:
    Description: VPC Id
    Type: AWS::EC2::VPC::Id
  WebServerDesiredCapacity:
    Default: '1'
    Description: Desired No of web server instances
    Type: Number
  WebServerInstanceType:
    ConstraintDescription: Choose an instance type. m3.medium or larger recommended.
    Default: m5.large
    Description: Web server instance type
    Type: String
  WebServerMaxSize:
    Default: '1'
    Description: Maximum No of web server instances
    Type: Number
  WebServerMinSize:
    Default: '1'
    Description: Minimum No of web server instances
    Type: Number
  DBSnapshotIdentifier:
    Default: ''
    Description: DN Snapshot ARN
    Type: String
  CustomMagentoAMI:
    Type: String
    Default: ''
    Description: Customer MAgento AMI to use when deploying
Conditions:
  UseAurora:
    !Equals
    - !Ref DBEngineType
    - Amazon Aurora
Resources:
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${QSS3BucketName}/${QSS3KeyPrefix}templates/securitygroups.template.yaml'
      Parameters:
        AccessCIDR: !Ref AccessCIDR
        VPCID: !Ref VPCID
        VPCCIDR: !Ref VPCCIDR

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub 
        - https://s3.amazonaws.com/${QSS3BucketName}/${QSS3KeyPrefix}templates/${RDSScriptName}
        - RDSScriptName:
            !If
            - UseAurora
            - aurora_mysql.template.yaml
            - rdsmysql.template.yaml

      Parameters:
        VPCID: !Ref VPCID
        CustomDBSecurityGroup: !GetAtt SecurityGroupStack.Outputs.MySQLRDSSecurityGroup
        Subnet1ID: !Ref PrivateSubnet1ID
        Subnet2ID: !Ref PrivateSubnet2ID
        DBAutoMinorVersionUpgrade: !Ref DBAutoMinorVersionUpgrade
        DBBackupRetentionPeriod: !Ref DBBackupRetentionPeriod
        DBInstanceClass: !Ref DBInstanceClass
        DBName: !Ref DBName
        DBMasterUsername: !Ref DBMasterUsername
        DBMasterUserPassword: !Ref DBMasterUserPassword
        DBMultiAZ: !Ref DBMultiAZ
        DBSnapshotIdentifier: !Ref DBSnapshotIdentifier
        
  ElastiCache:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${QSS3BucketName}/${QSS3KeyPrefix}templates/elasticache.template.yaml'
      Parameters:
        ElastiCacheSecurityGroup: !GetAtt SecurityGroupStack.Outputs.ElastiCacheSecurityGroup
        Subnet1ID: !Ref PrivateSubnet1ID
        Subnet2ID: !Ref PrivateSubnet2ID
        ElastiCacheNodes: !Ref ElastiCacheNodes
        ElastiCacheAutomaticFailover: !Ref ElastiCacheAutomaticFailover
        ElastiCacheNodeType: !Ref ElastiCacheNodeType
        
  WebServerASGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${QSS3BucketName}/${QSS3KeyPrefix}templates/webserver.template.yaml'
      Parameters:
        ELBSecurityGroup: !GetAtt SecurityGroupStack.Outputs.ELBSecurityGroup
        EFSSecurityGroup: !GetAtt SecurityGroupStack.Outputs.EFSSecurityGroup
        WebServerSecurityGroup: !GetAtt SecurityGroupStack.Outputs.WebServerSecurityGroup
        NotificationEmail: !Ref NotificationEmail
        WebServerMinSize: !Ref WebServerMinSize
        WebServerMaxSize: !Ref WebServerMaxSize
        WebServerInstanceType: !Ref WebServerInstanceType
        WebServerDesiredCapacity: !Ref WebServerDesiredCapacity
        WebServerSubnets: !Sub ${PrivateSubnet1ID},${PrivateSubnet2ID}
        ElasticLoadBalancerSubnets: !Sub ${PublicSubnet1ID},${PublicSubnet2ID}
        VPCID: !Ref VPCID
        MagentoCurrency: !Ref MagentoCurrency
        MagentoLanguage: !Ref MagentoLanguage
        MagentoTimezone: !Ref MagentoTimezone
        MagentoUsername: !Ref MagentoUsername
        MagentoPassword: !Ref MagentoPassword
        MagentoVersion: !Ref MagentoVersion
        DBMasterUserPassword: !Ref DBMasterUserPassword
        DBMasterUsername: !Ref DBMasterUsername
        DBName: !Ref DBName
        MySQLEndPointAddress:
            !If
            - UseAurora
            - !GetAtt RDSStack.Outputs.AuroraClusterEndpoint
            - !GetAtt RDSStack.Outputs.RDSEndPointAddress
        ElastiCacheEndpoint: !GetAtt ElastiCache.Outputs.ElastiCacheEndpoint
        DNSName: !Ref DNSName
        AdminFirstName: !Ref AdminFirstName
        AdminLastName: !Ref AdminLastName
        AdminEmail: !Ref AdminEmail
        AdminUserName: !Ref AdminUserName
        AdminPassword: !Ref AdminPassword
        SSLCertificateId: !Ref SSLCertificateId
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        CustomMagentoAMI: !Ref CustomMagentoAMI
Outputs:
  URL:
    Description: The URL of the website
    Value: !GetAtt WebServerASGStack.Outputs.URL
  AdminURL:
    Description: Admin path
    Value: !GetAtt WebServerASGStack.Outputs.AdminURL
  ELBURL:
    Description: The URL of the ELB, you should create a CNAME or alias to this name
      if you specified a DNS name
    Value: !GetAtt WebServerASGStack.Outputs.ELBURL
